# Generated by Django 5.0.6 on 2024-08-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newemail',
            name='image',
        ),
    ]
