# Generated by Django 5.0.6 on 2024-08-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_manager', '0002_remove_newemail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newemail',
            name='task_created_by',
        ),
    ]
